[features]
seeds = false

[programs.localnet]
anchor = "ANVbZZvJUDY6Dy5mMYraY6uD6aUcmSrKNYCFxfUBheYK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chalda/.config/solana/id.json"

[scripts]
test = "python -m pytest"
