[features]
seeds = false
[programs.localnet]
anchor = "ANVbZZvJUDY6Dy5mMYraY6uD6aUcmSrKNYCFxfUBheYK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chalda/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
